project:
  type: book

book:
  title: "EIT course - Get your dataset ready!"
  subtitle: "Using R and GIS"
  author: 
    - name: "Rosa Félix"
      email: rosamfelix@tecnico.pt
      orcid: 0000-0002-5642-6006
    - name: "Gabriel Valença"
      email: gabrielvalenca@tecnico.pt
      orcid: 0000-0002-3684-3005
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
  pdf:
    documentclass: scrreprt

editor: visual

