---
eval: false
---

# Grids

## Make grid

```{r}
#| message: false
#| warning: false
library(sf)
library(dplyr)
library(mapview)

MUNICIPIOSgeo = st_read("data/Municipalities_geo.gpkg")
LISBON = MUNICIPIOSgeo |> filter(Municipality == "Lisboa") |> st_transform(3857)
```

To make a grid we is the `st_make_grid()` function.

```{r}
GRID = LISBON |>
  st_make_grid(cellsize = 800, what = "polygons", square = TRUE) |> # 800m, we are using a projected crs
  st_sf() |> # from list to sf
  st_transform(crs = 4326) # to WGS84

GRID = GRID |>  
  mutate(id = c(1:nrow(GRID)))  # just to give an ID to each cell 

mapview(GRID)
```

## Count points in polygons


```{r}
SURVEY = read.csv("data/SURVEY.txt", sep = "\t")
SURVEYgeo = SURVEY |> st_as_sf(coords = c("lon", "lat"), crs = 4326)

SURVEY_with_GRIDid = SURVEYgeo |> 
  st_join(GRID, 
          join = st_intersects) |> 
    st_drop_geometry() |> 
    group_by(id) |> 
    summarise(count = n()) |> 
    ungroup()

# back to grid
GRIDdensity = GRID |> left_join(SURVEY_with_GRIDid)

mapview(GRIDdensity, zcol = "count")
```
