---
number-depth: 2
format:
  pdf:
    prefer-html: true
---

# Course Structure

The course consists of an in-person 2-day course, taking place during the EIT DTN Annual Meeting on the **19th and 20th September 2024**.

The first day will focus on learning the basics of R programming and how to treat and explore datasets.
The second day will focus on analyzing spatial datasets, and routing origins to destinations.

## Contents

### Day 1

#### Morning {.unnumbered}

We will start by a brief introduction to this course, followed by an introduction to programming techniques and data structures.

Then, we will install R and RStudio, and and the required R packages for this course, as in [Software](software.qmd) section.

After having everything setup, we will start with the [R basics](r-basics.qmd), with examples and exercises.

#### Afternoon {.unnumbered}

In the afternoon, we will focus on [data manipulation](data-manipulation.qmd), using the dplyr package to select, filter, left-join, group and summarize datasets.

Then, we will [introduce GIS and spatial data](spatial-data.qmd), learning how to importing and visualize vector data.

Finally, we will learn how to create cool [interactive maps](interactive-maps.qmd) using mapview and R markdown.

### Day 2

#### Morning {.unnumbered}

We will start the day by estimating the different types of [centroids of transport zones](centroids.qmd).

After this, the natural next step is to create [desire lines](desire-lines.qmd) from orgins and destinations of the transport zones.

We will then learn how to estimate [euclidean and routing distances](distances.qmd) for the desire-lines, using transport networks.

#### Afternoon {.unnumbered}

In the second afternoon, we will briefly learn where to find and extract [open transportation data](open-data.qmd), such as OpenStreetMap and GTFS.

Then, we will learn how to perform [accessibility analysis](r5r.qmd), using the r5r package.

And finally, to wrap up all this topics, we will have a group exercise using other complex datasets, where you will apply the knowledge learned during the course.

## Detailed schedule

| Day 1 |                                                                                                                 |
|---------|----------------------------------------------------------|
| 9.30  | Introductions and Presentation of the course contents                                                           |
| 10.00 | Introduction to programming techniques and data structures                                                      |
| 10.30 | Introduction to R and RStudio: hands-on to install software and main packages                                   |
| 11.00 | *Coffee break*                                                                                                  |
| 11.15 | (cont.)                                                                                                         |
| 11.30 | R basics: examples and exercises                                                                                |
|       |                                                                                                                 |
| 12.30 | *Lunch break*                                                                                                   |
|       |                                                                                                                 |
| 13.30 | Data manipulation: examples and exercises (select, filter, left-join, group and summarize, using dplyr package) |
| 15.30 | *Coffee break*                                                                                                  |
| 15.45 | Introduction to GIS and spatial data: import create vector data                                                 |
| 16.30 | View and export interactive maps                                                                                |
| 17.00 | *End of day 1*                                                                                                  |

| Day 2 |                                                                                    |
|----------|---------------------------------------------------------|
| 9.30  | Centroids of transport zones                                                       |
| 10.15 | Desire-lines from OD pairs and transport zones                                     |
| 11.00 | *Coffee break*                                                                     |
| 11.15 | (cont.)                                                                            |
| 11.30 | Euclidean and routing distances with sf and r5r                                    |
|       |                                                                                    |
| 12.30 | *Lunch break*                                                                      |
|       |                                                                                    |
| 13.30 | Open Transportation data: where to find it (OSM and GTFS)                          |
| 14.00 | Accessibility analysis with r5r                                                    |
| 16.00 | *Coffee break*                                                                     |
| 16.15 | Using you data: manipulation and spatial analysis methods and further applications |
| 16.45 | Survey and feedback from participants                                              |
| 17.00 | *End of day 2*                                                                     |

## Location

The course will take place at Campus Sterre, Building S8, room 2.4.

```{r}
#| fig-format: png
Campus_S8_coord = c(3.7105372, 51.0241258)
Campus_S8 = sf::st_sfc(sf::st_point(Campus_S8_coord)) # create point
Campus_S8 = sf::st_as_sf(Campus_S8, crs = 4326) # assign crs

mapview::mapview(Campus_S8, map.types = "OpenStreetMap") # quick map view
```

## Resources

-   You laptop, with any OS

-   Github repository with all the materials (data, code and guidelines)

-   Survey datasets, school locations and public transport operator datasets
